Completed string-manipulation-1 exercise.
ryan-byrnes/c0621-code-solutions pull request #36
Opened 2021-07-03 00:36 UTC by ryan-byrnes

![Screen Shot 2021-07-02 at 5 35 49 PM](https://user-images.githubusercontent.com/20606439/124338325-073f5f80-db5c-11eb-9de0-935b98d4b68f.png)

2021-07-06 17:26 UTC, codingcodymiller requested changes
Good start here! A couple notes for you:

2021-07-06 17:26 UTC, codingcodymiller commented on string-manipulation-1/src/get-words.js
> +  for (var i = 0; i < string.length; i++) {
This loop isn't necessary

2021-07-06 17:26 UTC, codingcodymiller commented on string-manipulation-1/src/is-vowel.js
> +  return /[aeiou]/.test(char.toLowerCase());
You should do this again without regex

2021-07-06 21:49 UTC, ryan-byrnes commented
![Screen Shot 2021-07-06 at 2 48 51 PM](https://user-images.githubusercontent.com/20606439/124670760-51c92080-de69-11eb-90c8-b41209723350.png)

2021-07-07 17:30 UTC, codingcodymiller approved these changes

2021-07-07 17:44 UTC, merged