Array manipulation 1 Ryan Byrnes
ryan-byrnes/c0621-code-solutions pull request #37
Opened 2021-07-05 16:17 UTC by ryan-byrnes

<img width="1241" alt="Screen Shot 2021-07-05 at 9 16 36 AM" src="https://user-images.githubusercontent.com/20606439/124498750-b903a980-dd71-11eb-9983-c80f8bf40623.png">

2021-07-06 17:45 UTC, codingcodymiller requested changes
Great start here! A couple minor notes:

2021-07-06 17:45 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +    if (i !== (array.length - 1)) {
Instead of having a conditional run with every iteration, you should just stop the loop one step earlier.

2021-07-06 17:45 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +    if (i > 0) {
Instead of having a conditional run with every iteration, you should just start the loop one step later.

2021-07-06 23:43 UTC, ryan-byrnes commented
![Screen Shot 2021-07-06 at 4 43 10 PM](https://user-images.githubusercontent.com/20606439/124679451-44b42d80-de79-11eb-8cdc-0ec22ead126a.png)

2021-07-07 17:33 UTC, codingcodymiller approved these changes

2021-07-07 17:43 UTC, merged