Completed javascript-timers
ryan-byrnes/c0621-code-solutions pull request #61
Opened 2021-07-20 23:44 UTC by ryan-byrnes

https://user-images.githubusercontent.com/20606439/126408798-30d3dff8-4d03-4125-8155-8fc05e1ca8e7.mov

2021-07-20 23:45 UTC, codingcodymiller requested changes

2021-07-20 23:45 UTC, codingcodymiller commented on javascript-timers/interval.js
> +  }
If you create a variable to decrement over time, I think you could do this without individual code blocks for each number

2021-07-21 00:03 UTC, ryan-byrnes commented
https://user-images.githubusercontent.com/20606439/126410081-9d04635f-d6e9-4941-aba0-f9e4447298f4.mov

2021-07-21 00:04 UTC, codingcodymiller approved these changes

2021-07-21 00:05 UTC, merged